name: Testing

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch: {}



jobs:
  required:
    name: "${{matrix.os}} / ${{matrix.python-version}} / numpy_nightly: ${{matrix.numpy_nightly}}"
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, "3.12"]
        numpy_nightly: [false, true]
    steps:
      - name: Check out github
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (python)
        run: |
          python -m pip install --upgrade pip wheel codecov

      - name: Install package
        run: |
          python -m pip install .[test]

      - name: Install numpy
        if: ${{ matrix.numpy_nightly }}
        run: |
          pip install -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple -U numpy

      - name: Run tests
        run: |
          pytest -v --cov --cov-report term

      - name: Upload codecoverage
        continue-on-error: true
        run: |
          codecov
